import x from 'fs';
import v from 'path';
import { fileURLToPath } from 'url';

var d={mode:"px",config:{".fsize":"font-size: $rpx",".bd":"border: $px solid #e1e5ee",".bgred":"background: red",".backcolor":"background-color: #"}};var r={".m":"margin:$px",".ml":"margin-left:$px",".mr":"margin-right:$px",".mt":"margin-top:$px",".mb":"margin-bottom:$px",".mx":"margin-left:$px;margin-right:$px",".my":"margin-top:$px;margin-bottom:$px",".mi":"margin:$px !important",".mli":"margin-left:$px !important",".mri":"margin-right:$px !important",".mti":"margin-top:$px !important",".mbi":"margin-bottom:$px !important",".mxi":"margin-left:$px !important;margin-right:$px !important",".myi":"margin-top:$px !important;margin-bottom:$px !important",".p":"padding:$px",".pl":"padding-left:$px",".pr":"padding-right:$px",".pt":"padding-top:$px",".pb":"padding-bottom:$px",".px":"padding-left:$px;padding-right:$px",".py":"padding-top:$px;padding-bottom:$px",".pi":"padding:$px !important",".pli":"padding-left:$px !important",".pri":"padding-right:$px !important",".pti":"padding-top:$px !important",".pbi":"padding-bottom:$px !important",".pxi":"padding-left:$px !important;padding-right:$px !important",".pyi":"padding-top:$px !important;padding-bottom:$px !important",".w":"width:$px",".wi":"width:$px !important",".mw":"min-width:$px",".wp":"width:$%",".wpi":"width:$% !important",".h":"height:$px",".hi":"height:$px !important",".mh":"min-height:$px",".hp":"height:$%",".hpi":"height:$% !important",".l":"left:$px",".r":"right:$px",".t":"top:$px",".b":"bottom:$px",".lh":"line-height:$px",".fs":"font-size:$px",".fw":"font-weight:$",".bgs":"background-size:$px",".br":"border-radius:$px",".c":"color: #",".bgc":"background-color: #",".z":"z-index: $"};r=Object.assign(r,d.config);var o="";for(let t in r){let i=r[t];i.indexOf("$")!=-1?o+=`\\${t}-[0-9]+|`:i.indexOf("#")!=-1?o+=`\\${t}-[0-9a-fA-F]+|`:o+=`\\${t}|`;}o=o.substr(0,o.length-1);function s(t){let i,n,p;try{i=t.match(/<template lang=("|')pug("|')>([\s\S]*)<\/template>/g),n=t.match(/<template>([\s\S]*)<\/template>/g),i?p=i[0]:n&&(p="."+(n[0].match(/class=("|')([a-zA-Z0-9 \- _]*)("|')/gi)||[]).map(e=>e.replace(/class=('|")|("|')/g,"").split(" ").join(".")).join("."));}catch(e){return console.warn(e),t}if(!p)return {code:t,css:[]};(p.match(/include \S*\.pug/g)||[]).forEach(e=>{let m=this.resourcePath.substr(0,this.resourcePath.lastIndexOf("/")+1)+e.replace("include ","");this.addDependency(m);let a=x.readFileSync(m,"utf-8");p=p.replace(e,a);});let h=new RegExp(o,"ig");function b(e,m,a){return a.indexOf(e)===m}let y=(p.match(h)||[]).filter(b),l=[];return y.forEach(e=>{if(r[e.split("-")[0]]&&r[e.split("-")[0]].indexOf("$")==-1&&r[e.split("-")[0]].indexOf("#")!=-1){let a=e.match(/\.\w+/)[0],g="#"+e.split("-")[1];l.push(`${e}{${r[a].replace(/\#/g,g)}}`);}else if(/\d+/.test(e)){let a=e.match(/\.\w+/)[0],g=+e.match(/\d+/)[0];l.push(`${e}{${r[a].replace(/\$/g,g)}}`);}else {let a=e;l.push(`${e}{${r[a]}}`);}}),{code:`${t}
<style>${l.join("")}</style>
`,css:l}}function u(){return v.dirname(fileURLToPath(import.meta.url))+"/"}var c={};function k(t,i,n){return n.indexOf(t)===i}function j(){let t=[];for(let i in c)t=t.concat(c[i]).filter(k);x.writeFileSync(u()+"atomcss-generated.css",t.join(""),"utf8");}var f=/\.(vue)$/;function O(){return {name:"vite-plugin-vue-atomcss",enforce:"pre",apply:"serve",transform(t,i){if(f.test(i))return {code:s(t).code}},transformIndexHtml(t){return [{tag:"script",attrs:{type:"module",src:u()+"client.js"},injectTo:"body"}]},handleHotUpdate({modules:t,server:i}){let n=t.filter(p=>f.test(p.id)).map(p=>p.id);if(n.length>0){let p=x.readFileSync(n[0],"utf8"),$=s(p);i.ws.send({type:"custom",event:"atomcss:update-style",data:{key:n[0],value:$.css.join("")}});}}}}function S(){return {name:"vite-plugin-vue-atomcss",enforce:"pre",apply:"build",transform(t,i){if(f.test(i)){let n=s(t);c[i]=n.css,j();}}}}function z(){return [O(),S()]}

export { z as default };
