'use strict';

var w = require('fs');

function _interopDefault (e) { return e && e.__esModule ? e : { default: e }; }

var w__default = /*#__PURE__*/_interopDefault(w);

var m={".m":"margin:$px",".ml":"margin-left:$px",".mr":"margin-right:$px",".mt":"margin-top:$px",".mb":"margin-bottom:$px",".mx":"margin-left:$px;margin-right:$px",".my":"margin-top:$px;margin-bottom:$px",".mi":"margin:$px !important",".mli":"margin-left:$px !important",".mri":"margin-right:$px !important",".mti":"margin-top:$px !important",".mbi":"margin-bottom:$px !important",".mxi":"margin-left:$px !important;margin-right:$px !important",".myi":"margin-top:$px !important;margin-bottom:$px !important",".p":"padding:$px",".pl":"padding-left:$px",".pr":"padding-right:$px",".pt":"padding-top:$px",".pb":"padding-bottom:$px",".px":"padding-left:$px;padding-right:$px",".py":"padding-top:$px;padding-bottom:$px",".pi":"padding:$px !important",".pli":"padding-left:$px !important",".pri":"padding-right:$px !important",".pti":"padding-top:$px !important",".pbi":"padding-bottom:$px !important",".pxi":"padding-left:$px !important;padding-right:$px !important",".pyi":"padding-top:$px !important;padding-bottom:$px !important",".w":"width:$px",".wi":"width:$px !important",".mw":"min-width:$px",".wp":"width:$%",".wpi":"width:$% !important",".h":"height:$px",".hi":"height:$px !important",".mh":"min-height:$px",".hp":"height:$%",".hpi":"height:$% !important",".l":"left:$px",".r":"right:$px",".t":"top:$px",".b":"bottom:$px",".lh":"line-height:$px",".fs":"font-size:$px",".fw":"font-weight:$",".bgs":"background-size:$px",".br":"border-radius:$px",".c":"color: #",".bgc":"background-color: #",".z":"z-index: $"},$="",x="",a=null;function h(e){if(!$||JSON.stringify(e)!=$){if($=JSON.stringify(e),e.mode==="rem")for(let t in m)m[t]=m[t].replace(/\$px/gi,"$rem");a={...m,...e.config||{}};let i=[];for(let t in a){let n=a[t];n.indexOf("$")!=-1?i.push(`\\${t}-[0-9]+`):n.indexOf("#")!=-1?i.push(`\\${t}-[0-9a-fA-F]+`):i.push(`\\${t}`);}return i.sort((t,n)=>n.length-t.length),x=i.join("|"),x}else return x}function y(e){let i="",t="",n="";try{i=e.match(/<template lang=("|')pug("|')>([\s\S]*)<\/template>/g),t=e.match(/<template>([\s\S]*)<\/template>/g),i?n=i[0]:t&&(n="."+(t[0].match(/class=("|')([a-zA-Z0-9 \- _]*)("|')/gi)||[]).map(p=>p.replace(/class=('|")|("|')/g,"").split(" ").join(".")).join("."));}catch(p){return console.warn(p),""}return n}function b(e,i){let t=new RegExp(e,"ig");function n(l,c,r){return r.indexOf(l)===c}let p=(i.match(t)||[]).filter(n),s=[];return p.forEach(l=>{if(a[l.split("-")[0]]&&a[l.split("-")[0]].indexOf("$")==-1&&a[l.split("-")[0]].indexOf("#")!=-1&&/^[0-9a-fA-F]+$/.test(l.split("-")[1])){let r=l.split("-");if(r.length>1){let o=r.slice(0,r.length-1).join("-"),d="#"+r[r.length-1];a[o]&&s.push(`${l}{${a[o].replace(/\#/g,d)}}`);}}else if(/\d+/.test(l)){let r=l.split("-");if(r.length>1){let o=r.slice(0,r.length-1).join("-"),d=r[r.length-1];a[o]&&s.push(`${l}{${a[o].replace(/\$/g,d)}}`);}}else {let r=l;a[r]&&s.push(`${l}{${a[r]}}`);}}),s}function g(e,i={}){let t=h(i),n=y(e);if(!n)return {code:e,css:[]};let p=b(t,n);return {code:`${e}
<style>${p.join("")}</style>
`,css:p}}var u={};function v(e,i,t){return t.indexOf(e)===i}function S(){let e=[];for(let i in u)e=e.concat(u[i]).filter(v);return e.join("")}var f=/\.(vue)$/;function F(e){return {name:"vite-plugin-vue-atomcss",enforce:"pre",apply:"serve",transform(i,t){if(f.test(t))return {code:g(i,e).code}},transformIndexHtml(i){return [{tag:"script",attrs:{type:"module",src:"/node_modules/vite-plugin-vue-atomcss/client.js"},injectTo:"body"}]},handleHotUpdate({modules:i,server:t}){let n=i.filter(p=>f.test(p.id)).map(p=>p.id);if(n.length>0){let p=w__default.default.readFileSync(n[0],"utf8"),s=g(p,e);t.ws.send({type:"custom",event:"atomcss:update-style",data:{key:n[0],value:s.css.join("")}});}}}}function j(e){let i;return {name:"vite-plugin-vue-atomcss",enforce:"pre",apply:"build",transform(t,n){if(f.test(n)){let p=g(t,e);u[n]=p.css;}},renderStart(){let t=this.emitFile({type:"asset",name:"atomcss-dist.css",source:S()});i=this.getFileName(t);},transformIndexHtml(t){return [{tag:"link",attrs:{rel:"stylesheet",href:"/"+i},injectTo:"head"}]}}}function A(e){return [F(e),j(e)]}

module.exports = A;
