'use strict';

var u = require('fs');
var w = require('path');
var url = require('url');

function _interopDefault (e) { return e && e.__esModule ? e : { default: e }; }

var u__default = /*#__PURE__*/_interopDefault(u);
var w__default = /*#__PURE__*/_interopDefault(w);

var a={".m":"margin:$px",".ml":"margin-left:$px",".mr":"margin-right:$px",".mt":"margin-top:$px",".mb":"margin-bottom:$px",".mx":"margin-left:$px;margin-right:$px",".my":"margin-top:$px;margin-bottom:$px",".mi":"margin:$px !important",".mli":"margin-left:$px !important",".mri":"margin-right:$px !important",".mti":"margin-top:$px !important",".mbi":"margin-bottom:$px !important",".mxi":"margin-left:$px !important;margin-right:$px !important",".myi":"margin-top:$px !important;margin-bottom:$px !important",".p":"padding:$px",".pl":"padding-left:$px",".pr":"padding-right:$px",".pt":"padding-top:$px",".pb":"padding-bottom:$px",".px":"padding-left:$px;padding-right:$px",".py":"padding-top:$px;padding-bottom:$px",".pi":"padding:$px !important",".pli":"padding-left:$px !important",".pri":"padding-right:$px !important",".pti":"padding-top:$px !important",".pbi":"padding-bottom:$px !important",".pxi":"padding-left:$px !important;padding-right:$px !important",".pyi":"padding-top:$px !important;padding-bottom:$px !important",".w":"width:$px",".wi":"width:$px !important",".mw":"min-width:$px",".wp":"width:$%",".wpi":"width:$% !important",".h":"height:$px",".hi":"height:$px !important",".mh":"min-height:$px",".hp":"height:$%",".hpi":"height:$% !important",".l":"left:$px",".r":"right:$px",".t":"top:$px",".b":"bottom:$px",".lh":"line-height:$px",".fs":"font-size:$px",".fw":"font-weight:$",".bgs":"background-size:$px",".br":"border-radius:$px",".c":"color: #",".bgc":"background-color: #",".z":"z-index: $"},m=null,d="";function h(e){if(m)return d;{if(m=e,m.mode==="rem")for(let t in a)a[t]=a[t].replace(/\$px/gi,"$rem");a=Object.assign(a,m.config||{});let i=[];for(let t in a){let p=a[t];p.indexOf("$")!=-1?i.push(`\\${t}-[0-9]+`):p.indexOf("#")!=-1?i.push(`\\${t}-[0-9a-fA-F]+`):i.push(`\\${t}`);}return i.sort((t,p)=>p.length-t.length),d=i.join("|"),d}}function b(e){let i="",t="",p="";try{i=e.match(/<template lang=("|')pug("|')>([\s\S]*)<\/template>/g),t=e.match(/<template>([\s\S]*)<\/template>/g),i?p=i[0]:t&&(p="."+(t[0].match(/class=("|')([a-zA-Z0-9 \- _]*)("|')/gi)||[]).map(r=>r.replace(/class=('|")|("|')/g,"").split(" ").join(".")).join("."));}catch(r){return console.warn(r),""}return p}function y(e,i){let t=new RegExp(e,"ig");function p(n,f,o){return o.indexOf(n)===f}let r=(i.match(t)||[]).filter(p),l=[];return r.forEach(n=>{if(a[n.split("-")[0]]&&a[n.split("-")[0]].indexOf("$")==-1&&a[n.split("-")[0]].indexOf("#")!=-1&&/^[0-9a-fA-F]+$/.test(n.split("-")[1])){let o=n.match(/\.\w+/)[0],g="#"+n.split("-")[1];l.push(`${n}{${a[o].replace(/\#/g,g)}}`);}else if(/\d+/.test(n)){let o=n.match(/\.\w+/)[0],g=+n.match(/\d+/)[0];l.push(`${n}{${a[o].replace(/\$/g,g)}}`);}else {let o=n;l.push(`${n}{${a[o]}}`);}}),l}function s(e,i={}){let t=h(i),p=b(e);if(!p)return {code:e,css:[]};let r=y(t,p);return {code:`${e}
<style>${r.join("")}</style>
`,css:r}}function c(){return w__default.default.dirname(url.fileURLToPath((typeof document === 'undefined' ? require('u' + 'rl').pathToFileURL(__filename).href : (document.currentScript && document.currentScript.src || new URL('out.js', document.baseURI).href))))+"/"}var $={};function A(e,i,t){return t.indexOf(e)===i}function C(){let e=[];for(let i in $)e=e.concat($[i]).filter(A);u__default.default.writeFileSync(c()+"atomcss-generated.css",e.join(""),"utf8");}var x=/\.(vue)$/;function S(e){return {name:"vite-plugin-vue-atomcss",enforce:"pre",apply:"serve",transform(i,t){if(x.test(t))return {code:s(i,e).code}},transformIndexHtml(i){return [{tag:"script",attrs:{type:"module",src:c()+"client.js"},injectTo:"body"}]},handleHotUpdate({modules:i,server:t}){let p=i.filter(r=>x.test(r.id)).map(r=>r.id);if(p.length>0){let r=u__default.default.readFileSync(p[0],"utf8"),l=s(r,e);t.ws.send({type:"custom",event:"atomcss:update-style",data:{key:p[0],value:l.css.join("")}});}}}}function F(e){return {name:"vite-plugin-vue-atomcss",enforce:"pre",apply:"build",transform(i,t){if(x.test(t)){let p=s(i,e);$[t]=p.css,C();}}}}function j(e){return [S(e),F(e)]}

module.exports = j;
